import type { CalendarPost } from "~/types/social-media";

export function getCalendarPosts(): CalendarPost[] {
  return [
    // Published posts (past dates in Feb 2026)
    {
      id: "cal-1",
      platform: "tiktok",
      title: "POV: Du bist der letzte im Büro um 23 Uhr",
      type: "video",
      scheduledAt: "2026-02-01T19:00:00",
      status: "published",
      performance: { views: 14_800_000, likes: 1_240_000, comments: 48_000 },
    },
    {
      id: "cal-2",
      platform: "youtube",
      title: "Die Wahrheit über Social Media Einnahmen in Deutschland",
      type: "video",
      scheduledAt: "2026-02-01T17:00:00",
      status: "published",
      performance: { views: 890_000, likes: 72_000, comments: 18_700 },
    },
    {
      id: "cal-3",
      platform: "instagram",
      title: "Montags-Motivation: 5 Tipps für produktive Wochen",
      type: "reel",
      scheduledAt: "2026-02-03T12:00:00",
      status: "published",
      performance: { views: 420_000, likes: 38_000, comments: 2_100 },
    },
    {
      id: "cal-4",
      platform: "tiktok",
      title: "Wenn dein Algorithmus dich besser kennt als deine Freunde",
      type: "video",
      scheduledAt: "2026-02-04T19:30:00",
      status: "published",
      performance: { views: 6_200_000, likes: 892_000, comments: 31_000 },
    },
    {
      id: "cal-5",
      platform: "snapchat",
      title: "Tagesroutine als Content Creator - ungeschnitten",
      type: "story",
      scheduledAt: "2026-02-05T10:00:00",
      status: "published",
      performance: { views: 89_000, likes: 12_000, comments: 340 },
    },
    {
      id: "cal-6",
      platform: "instagram",
      title: "Behind the Scenes: Mein neues Studio Setup",
      type: "image",
      scheduledAt: "2026-02-06T14:00:00",
      status: "published",
      performance: { views: 310_000, likes: 45_000, comments: 3_200 },
    },
    {
      id: "cal-7",
      platform: "tiktok",
      title: "Deutsch lernen mit Memes - Teil 46",
      type: "video",
      scheduledAt: "2026-02-07T20:00:00",
      status: "published",
      performance: { views: 5_400_000, likes: 623_000, comments: 18_000 },
    },
    {
      id: "cal-8",
      platform: "youtube",
      title: "Q&A: Eure Fragen zum Creator-Alltag beantwortet",
      type: "live",
      scheduledAt: "2026-02-08T18:00:00",
      status: "published",
      performance: { views: 340_000, likes: 28_000, comments: 12_400 },
    },
    {
      id: "cal-9",
      platform: "snapchat",
      title: "Behind the Scenes: Videodreh in den Alpen",
      type: "spotlight",
      scheduledAt: "2026-02-09T11:00:00",
      status: "published",
      performance: { views: 340_000, likes: 41_000, comments: 890 },
    },
    {
      id: "cal-10",
      platform: "instagram",
      title: "Meine ehrliche Morning Routine als Content Creator",
      type: "reel",
      scheduledAt: "2026-02-10T08:00:00",
      status: "published",
      performance: { views: 680_000, likes: 487_000, comments: 5_600 },
    },
    {
      id: "cal-11",
      platform: "tiktok",
      title: "3 Apps die JEDER Content Creator braucht",
      type: "video",
      scheduledAt: "2026-02-11T19:00:00",
      status: "published",
      performance: { views: 3_100_000, likes: 284_000, comments: 9_400 },
    },
    {
      id: "cal-12",
      platform: "instagram",
      title: "Vorher/Nachher: Mein Setup-Upgrade 2026",
      type: "image",
      scheduledAt: "2026-02-12T13:00:00",
      status: "published",
      performance: { views: 290_000, likes: 52_000, comments: 4_100 },
    },
    {
      id: "cal-13",
      platform: "tiktok",
      title: "Was passiert wenn man 24h nur KI-Content postet",
      type: "video",
      scheduledAt: "2026-02-13T20:00:00",
      status: "published",
      performance: { views: 7_800_000, likes: 945_000, comments: 42_000 },
    },
    {
      id: "cal-14",
      platform: "tiktok",
      title: "Deutsch lernen mit Memes - Teil 47",
      type: "video",
      scheduledAt: "2026-02-14T19:00:00",
      status: "published",
      performance: { views: 8_900_000, likes: 1_020_000, comments: 27_000 },
    },
    {
      id: "cal-15",
      platform: "instagram",
      title: "Valentinstag Special: Creator-Couples im Interview",
      type: "reel",
      scheduledAt: "2026-02-14T12:00:00",
      status: "published",
      performance: { views: 520_000, likes: 68_000, comments: 7_800 },
    },
    {
      id: "cal-16",
      platform: "snapchat",
      title: "Valentinstag Chaos - Was ist schief gegangen",
      type: "story",
      scheduledAt: "2026-02-15T09:00:00",
      status: "published",
      performance: { views: 124_000, likes: 18_000, comments: 620 },
    },
    {
      id: "cal-17",
      platform: "youtube",
      title: "Ich habe 30 Tage nur mit KI gearbeitet - Das Ergebnis",
      type: "video",
      scheduledAt: "2026-02-16T17:00:00",
      status: "published",
      performance: { views: 2_340_000, likes: 186_000, comments: 14_200 },
    },

    // Scheduled posts (future dates)
    {
      id: "cal-18",
      platform: "tiktok",
      title: "Warum Deutschland TikTok dominiert - Analyse",
      type: "video",
      scheduledAt: "2026-02-18T19:00:00",
      status: "scheduled",
    },
    {
      id: "cal-19",
      platform: "instagram",
      title: "Wochenrückblick: Die besten Momente #KW8",
      type: "reel",
      scheduledAt: "2026-02-19T12:00:00",
      status: "scheduled",
    },
    {
      id: "cal-20",
      platform: "youtube",
      title: "YouTube Shorts vs. TikTok: Welche Plattform zahlt mehr?",
      type: "short",
      scheduledAt: "2026-02-20T17:00:00",
      status: "scheduled",
    },
    {
      id: "cal-21",
      platform: "tiktok",
      title: "Deutsch lernen mit Memes - Teil 48",
      type: "video",
      scheduledAt: "2026-02-21T19:00:00",
      status: "scheduled",
    },
    {
      id: "cal-22",
      platform: "snapchat",
      title: "Wochenend-Vlog: Content Creation Marathon",
      type: "spotlight",
      scheduledAt: "2026-02-22T11:00:00",
      status: "scheduled",
    },
    {
      id: "cal-23",
      platform: "instagram",
      title: "Mein Workflow für 100 Content-Ideen pro Monat",
      type: "image",
      scheduledAt: "2026-02-23T14:00:00",
      status: "scheduled",
    },
    {
      id: "cal-24",
      platform: "tiktok",
      title: "POV: Dein Chef entdeckt deinen TikTok Account",
      type: "video",
      scheduledAt: "2026-02-24T20:00:00",
      status: "scheduled",
    },
    {
      id: "cal-25",
      platform: "youtube",
      title: "Creator Economy 2026: Trends und Prognosen",
      type: "video",
      scheduledAt: "2026-02-25T17:00:00",
      status: "scheduled",
    },
    {
      id: "cal-26",
      platform: "instagram",
      title: "10 Fehler die ich als Anfänger gemacht habe",
      type: "reel",
      scheduledAt: "2026-02-26T12:00:00",
      status: "scheduled",
    },
    {
      id: "cal-27",
      platform: "tiktok",
      title: "Storytime: Mein erstes virales Video",
      type: "video",
      scheduledAt: "2026-02-27T19:00:00",
      status: "scheduled",
    },

    // Draft posts (not yet scheduled)
    {
      id: "cal-28",
      platform: "youtube",
      title: "Dokumentation: 1 Monat als digitaler Nomade in Lissabon",
      type: "video",
      scheduledAt: "2026-02-28T17:00:00",
      status: "draft",
    },
    {
      id: "cal-29",
      platform: "instagram",
      title: "Kollaboration mit @MaxVibes - Teaser",
      type: "reel",
      scheduledAt: "2026-02-28T12:00:00",
      status: "draft",
    },
    {
      id: "cal-30",
      platform: "tiktok",
      title: "Wie ich mit Hate-Kommentaren umgehe",
      type: "video",
      scheduledAt: "2026-02-28T19:00:00",
      status: "draft",
    },
  ];
}
